import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ThemeProvider, type Theme } from '@/context/ThemeProvider';
import { LanguageProvider } from '@/context/LanguageProvider';
import Header from '@/components/layout/Header';
import { cookies } from 'next/headers';
import type { AvailableLanguage } from '@/lib/i18n';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Javier Web 2025',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const cookieLang = cookieStore.get('portfolio:lang')?.value as AvailableLanguage | undefined;
  const initialLanguage: AvailableLanguage = cookieLang === 'en' ? 'en' : 'es';
  const themeCookie = cookieStore.get('portfolio:theme')?.value as Theme | undefined;
  const themeAppliedCookie = cookieStore.get('portfolio:theme-applied')?.value as 'light' | 'dark' | undefined;
  const initialThemePreference: Theme = themeCookie && ['light', 'dark', 'system'].includes(themeCookie) ? themeCookie : 'system';
  const initialAppliedTheme: 'light' | 'dark' =
    themeAppliedCookie === 'dark'
      ? 'dark'
      : themeAppliedCookie === 'light'
        ? 'light'
        : initialThemePreference === 'dark'
          ? 'dark'
          : 'light';
  return (
    <html lang={initialLanguage} data-theme={initialAppliedTheme}>
      <head>
        {/* Script anti-FOUC: aplica el tema antes de que React monte */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var themePref = localStorage.getItem('theme');
                  var appliedTheme = themePref;
                  if (!appliedTheme || appliedTheme === 'system') {
                    appliedTheme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
                  }
                  document.documentElement.setAttribute('data-theme', appliedTheme);
                  document.cookie = 'portfolio:theme=' + (themePref || 'system') + '; path=/; max-age=31536000';
                  document.cookie = 'portfolio:theme-applied=' + appliedTheme + '; path=/; max-age=31536000';
                  var lng = localStorage.getItem('portfolio:lang');
                  if (lng && (lng === 'en' || lng === 'es')) {
                    document.documentElement.setAttribute('lang', lng);
                    document.cookie = 'portfolio:lang=' + lng + '; path=/; max-age=31536000';
                  }
                } catch(e) {}
              })();
            `,
          }}
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <LanguageProvider initialLanguage={initialLanguage}>
          <ThemeProvider initialThemePreference={initialThemePreference} initialAppliedTheme={initialAppliedTheme}>
            <Header />
            <main>{children}</main>
          </ThemeProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
